version: '3'
services:
  api-tickets:
    build:
      context: .
    image: api-tickets:latest
    container_name: api-tickets
    volumes:
      - .:/app
    ports:
      - ${PHP_HOST_PORT}:8000
    depends_on:
      db: 
        condition: service_healthy
    entrypoint:
       ["/bin/bash", "-c" , 
          "cd /app
        && composer install
        && php artisan migrate:fresh --seed --seeder=PermissionsSeeder 
        && php artisan migrate --seed   
        && php artisan serve --host=0.0.0.0 --port=8000"]
    
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${POSTGRES_CONTAINER_NAME}
    ports:
      - "${DB_PORT}:5432"
    environment:
      - PGDATA=${POSTGRES_DATA}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - PGUSER=${DB_USERNAME}
    volumes:
      - pgdata:${POSTGRES_VOL}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
volumes:
  pgdata: