version: '3'
services:
  api-ingressos:
    image: api-ingressos:latest
    container_name: api-ingressos
    ports:
      - "${PHP_APACHE_HOST_PORT}:80"
    volumes:
      - .:${PHP_APACHE_VOL} 
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres-ingressos
    ports:
      - "${DB_PORT}:5432"
    environment:
      - PGDATA=${PGDATA}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
    volumes:
      - pgdata:${POSTGRES_VOL}
volumes:
  pgdata: